"""Repository contract sketches.

These are not drop-in files. They define the intended surface area so the coding agent keeps route handlers thin.
"""

from typing import Protocol


class OperationRepository(Protocol):
    async def create(self, *, operation_type: str, resource_type: str, resource_id: str | None, requested_by_user_id: str | None, metadata: dict) -> object: ...
    async def get(self, operation_id: str) -> object | None: ...
    async def list(self, *, resource_type: str | None = None, resource_id: str | None = None, status: str | None = None, limit: int = 50) -> list[object]: ...
    async def mark_running(self, operation_id: str) -> object: ...
    async def mark_succeeded(self, operation_id: str) -> object: ...
    async def mark_failed(self, operation_id: str, error_message: str) -> object: ...


class LightRAGDomainRepository(Protocol):
    async def create(self, *, domain_id: str, display_name: str, created_by_user_id: str | None, metadata: dict) -> object: ...
    async def get(self, domain_id: str) -> object | None: ...
    async def list(self, *, include_deleted: bool = False) -> list[object]: ...
    async def set_state(self, domain_id: str, state: str, error_message: str | None = None) -> object: ...
    async def set_health(self, domain_id: str, health_status: str, metadata_patch: dict | None = None) -> object: ...


class DocumentStructureRepository(Protocol):
    async def list_sections(self, document_id: str) -> list[object]: ...
    async def list_blocks(self, document_id: str) -> list[object]: ...
    async def list_assets(self, document_id: str) -> list[object]: ...
    async def build_section_tree(self, document_id: str) -> dict: ...
