from pathlib import Path

from app.lightrag_deploy.models import LightRAGDomain
from app.lightrag_deploy.paths import DomainPaths
from app.lightrag_deploy.settings import LightRAGDeploySettings


def write_domain_env(
    domain: LightRAGDomain,
    settings: LightRAGDeploySettings,
    paths: DomainPaths,
) -> None:
    del settings
    paths.env_file.parent.mkdir(parents=True, exist_ok=True)
    paths.env_file.write_text(render_domain_env(domain), encoding="utf-8")


def render_domain_env(domain: LightRAGDomain) -> str:
    return (
        "# Generated by Context Engine. Do not edit by hand.\n"
        "# Source of truth: root .env + .data/lightrag/domains.json\n"
        f"# Domain: {domain.id}\n"
        "\n"
        f"WORKSPACE={domain.id}\n"
        "HOST=0.0.0.0\n"
        f"PORT={domain.container_port}\n"
        "INPUT_DIR=/app/data/inputs\n"
        "WORKING_DIR=/app/data/rag_storage\n"
        "LOG_DIR=/app/data/logs\n"
    )


class ComposeGenerator:
    def __init__(self, settings: LightRAGDeploySettings):
        self.settings = settings

    def write(self, domains: list[LightRAGDomain]) -> None:
        self.settings.compose_file.parent.mkdir(parents=True, exist_ok=True)
        self.settings.compose_file.write_text(self.render(domains), encoding="utf-8")

    def render(self, domains: list[LightRAGDomain]) -> str:
        lines = [
            "# Generated by Context Engine. Do not edit by hand.",
            "# Source of truth: root .env + .data/lightrag/domains.json",
            "services:",
        ]
        for domain in sorted(domains, key=lambda item: item.id):
            lines.extend(self._service_lines(domain))
        lines.extend(
            [
                "networks:",
                f"  {self.settings.docker_network}:",
                f"    name: {self.settings.docker_network}",
                "",
            ]
        )
        return "\n".join(lines)

    def _service_lines(self, domain: LightRAGDomain) -> list[str]:
        paths = domain.paths
        return [
            f"  {domain.service_name}:",
            f"    image: {self.settings.image}",
            f"    container_name: {domain.container_name}",
            "    env_file:",
            f"      - {paths['env_file']}",
            "    ports:",
            f'      - "{domain.host}:{domain.host_port}:{domain.container_port}"',
            "    volumes:",
            f"      - {paths['inputs']}:/app/data/inputs",
            f"      - {paths['rag_storage']}:/app/data/rag_storage",
            f"      - {paths['artifacts']}:/app/data/artifacts",
            f"      - {paths['logs']}:/app/data/logs",
            "    networks:",
            f"      - {self.settings.docker_network}",
        ]


def path_to_posix(path: str | Path) -> str:
    return Path(path).as_posix()
