from pathlib import Path

from app.lightrag_deploy.models import LightRAGDomain
from app.lightrag_deploy.paths import DomainPaths
from app.lightrag_deploy.settings import LightRAGDeploySettings


def _append_env(lines: list[str], key: str, value: object | None) -> None:
    if value is None:
        return
    if isinstance(value, str) and not value.strip():
        return
    if isinstance(value, bool):
        rendered = "true" if value else "false"
    else:
        rendered = str(value)
    lines.append(f"{key}={rendered}")


def _append_provider_env(lines: list[str], settings: LightRAGDeploySettings | None) -> None:
    if settings is None:
        return

    lines.append("")
    lines.append("# Model provider configuration")
    _append_env(lines, "LLM_BINDING", settings.llm_binding)
    _append_env(lines, "LLM_BINDING_HOST", settings.llm_binding_host)
    _append_env(lines, "LLM_BINDING_API_KEY", settings.llm_binding_api_key)
    _append_env(lines, "LLM_MODEL", settings.llm_model)
    _append_env(lines, "KEYWORD_LLM_MODEL", settings.keyword_llm_model)
    _append_env(lines, "QUERY_LLM_MODEL", settings.query_llm_model)
    _append_env(lines, "VLM_LLM_MODEL", settings.vlm_llm_model)

    lines.append("")
    lines.append("# Embedding provider configuration")
    _append_env(lines, "EMBEDDING_BINDING", settings.embedding_binding)
    _append_env(lines, "EMBEDDING_BINDING_HOST", settings.embedding_binding_host)
    _append_env(lines, "EMBEDDING_BINDING_API_KEY", settings.embedding_binding_api_key)
    _append_env(lines, "EMBEDDING_MODEL", settings.embedding_model)
    _append_env(lines, "EMBEDDING_DIM", settings.embedding_dim)
    _append_env(lines, "EMBEDDING_TOKEN_LIMIT", settings.embedding_token_limit)
    _append_env(lines, "EMBEDDING_SEND_DIM", settings.embedding_send_dim)
    _append_env(lines, "EMBEDDING_USE_BASE64", settings.embedding_use_base64)

    lines.append("")
    lines.append("# OpenAI-compatible provider tuning")
    _append_env(lines, "OPENAI_LLM_MAX_TOKENS", settings.openai_llm_max_tokens)
    _append_env(lines, "OPENAI_LLM_MAX_COMPLETION_TOKENS", settings.openai_llm_max_completion_tokens)
    _append_env(lines, "OPENAI_LLM_TEMPERATURE", settings.openai_llm_temperature)
    _append_env(lines, "OPENAI_LLM_EXTRA_BODY", settings.openai_llm_extra_body)


def write_domain_env(
    domain: LightRAGDomain,
    settings: LightRAGDeploySettings,
    paths: DomainPaths,
) -> None:
    paths.env_file.parent.mkdir(parents=True, exist_ok=True)
    paths.env_file.write_text(render_domain_env(domain, settings), encoding="utf-8")


def render_domain_env(
    domain: LightRAGDomain,
    settings: LightRAGDeploySettings | None = None,
) -> str:
    lines = [
        "# Generated by Context Engine. Do not edit by hand.",
        "# Source of truth: root .env + .data/lightrag/domains.json",
        f"# Domain: {domain.id}",
        "",
        f"WORKSPACE={domain.workspace or domain.id}",
        "HOST=0.0.0.0",
        f"PORT={domain.container_port}",
        "INPUT_DIR=/app/data/inputs",
        "WORKING_DIR=/app/data/rag_storage",
        "LOG_DIR=/app/data/logs",
    ]
    if domain.postgres_database and domain.postgres_user:
        lines.extend(
            [
                "LIGHTRAG_KV_STORAGE=PGKVStorage",
                "LIGHTRAG_DOC_STATUS_STORAGE=PGDocStatusStorage",
                "LIGHTRAG_GRAPH_STORAGE=PGGraphStorage",
                "LIGHTRAG_VECTOR_STORAGE=PGVectorStorage",
                f"POSTGRES_HOST={(settings.postgres_host if settings else 'postgres')}",
                f"POSTGRES_PORT={(settings.postgres_port if settings else 5432)}",
                f"POSTGRES_DATABASE={settings.runtime_postgres_database if settings else domain.postgres_database}",
                f"POSTGRES_USER={settings.runtime_postgres_user if settings else domain.postgres_user}",
                f"POSTGRES_PASSWORD={(settings.runtime_postgres_password if settings else 'lightrag')}",
                "POSTGRES_VECTOR_INDEX_TYPE=HNSW",
            ]
        )
    _append_provider_env(lines, settings)
    return "\n".join(lines) + "\n"


class ComposeGenerator:
    def __init__(self, settings: LightRAGDeploySettings):
        self.settings = settings

    def write(self, domains: list[LightRAGDomain]) -> None:
        self.settings.compose_file.parent.mkdir(parents=True, exist_ok=True)
        self.settings.compose_file.write_text(self.render(domains), encoding="utf-8")

    def render(self, domains: list[LightRAGDomain]) -> str:
        lines = [
            "# Generated by Context Engine. Do not edit by hand.",
            "# Source of truth: root .env + .data/lightrag/domains.json",
            "services:",
        ]
        for domain in sorted(domains, key=lambda item: item.id):
            lines.extend(self._service_lines(domain))
        lines.extend(
            [
                "networks:",
                f"  {self.settings.docker_network}:",
                f"    name: {self.settings.docker_network}",
                "",
            ]
        )
        return "\n".join(lines)

    def _service_lines(self, domain: LightRAGDomain) -> list[str]:
        paths = domain.paths
        env_file = self._host_path(paths["env_file"])
        inputs = self._host_path(paths["inputs"])
        rag_storage = self._host_path(paths["rag_storage"])
        artifacts = self._host_path(paths["artifacts"])
        logs = self._host_path(paths["logs"])
        lines = [
            f"  {domain.service_name}:",
            f"    container_name: {domain.container_name}",
        ]
        if self.settings.build_context and self.settings.dockerfile:
            build_context = self._host_path(path_to_posix(self.settings.build_context))
            dockerfile = self._host_path(path_to_posix(self.settings.dockerfile))
            lines.extend(
                [
                    "    build:",
                    f"      context: {build_context}",
                    f"      dockerfile: {dockerfile}",
                ]
            )
        else:
            lines.append(f"    image: {self.settings.image}")
        lines.extend(
            [
                "    env_file:",
                f"      - {env_file}",
                "    ports:",
                f'      - "{domain.host}:{domain.host_port}:{domain.container_port}"',
                "    volumes:",
                f"      - {inputs}:/app/data/inputs",
                f"      - {rag_storage}:/app/data/rag_storage",
                f"      - {artifacts}:/app/data/artifacts",
                f"      - {logs}:/app/data/logs",
                "    networks:",
                f"      - {self.settings.docker_network}",
            ]
        )
        return lines

    @staticmethod
    def _host_path(raw_path: str) -> str:
        candidate = Path(raw_path).expanduser()
        if candidate.is_absolute():
            return candidate.resolve().as_posix()
        return (Path.cwd() / candidate).resolve().as_posix()


def path_to_posix(path: str | Path) -> str:
    return Path(path).as_posix()
